const mongoose = require('mongoose');

const InventoryTrack = new mongoose.Schema({
    ITEM_ID: Number,
    ITEM_NAME: String,
    ACTION_LOG: String,
    AADED_BY: String,
    INVENTORY_CATEGORY_ID: Number,
    INVENTRY_SUB_CATEGORY_ID: Number,
    DATE_OF_ENTRY: Date,
    STATUS: { type: Boolean, default: false },
    SELLING_PRICE: String,
    DESCRIPTION: String,
    INVENTORY_CATEGORY_NAME: String,
    INVENTRY_SUB_CATEGORY_NAME: String,
    BASE_UNIT_ID: Number,
    BASE_UNIT_NAME: String,
    BASE_QUANTITY: Number,
    PARENT_ID: Number,
    SHORT_CODE: String,
    AVG_LEVEL: String,
    REORDER_STOCK_LEVEL: String,
    ALERT_STOCK_LEVEL: String,
    HSN_ID: Number,
    HSN_NAME: String,
    TAX_PREFERENCE: String,
    TAX_ID: Number,
    TAX_NAME: String,
    IS_HAVE_VARIANTS: { type: Boolean, default: false },
    IS_SET: { type: Boolean, default: false },
    SKU_CODE: String,
    IS_NEW: { type: Boolean, default: false },
    VARIANT_COMBINATION: String,
    INVENTORY_TRACKING_TYPE: String,
    WARRANTY_ALLOWED: { type: Boolean, default: false },
    GUARANTEE_ALLOWED: { type: Boolean, default: false },
    EXPIRY_DATE_ALLOWED: { type: Boolean, default: false },
    INVENTORY_TYPE: String,
    RETURN_ALOW: { type: Boolean, default: false },
    BRAND_ID: Number,
    BRAND_NAME: String,
    WARRANTY_PERIOD: Number,
    GUARANTEE_PERIOD: Number,
    DISCOUNT_ALLOWED: { type: Boolean, default: false },
    DISCOUNTED_PRICE: String,
    RETURN_ALLOW_PERIOD: Number,
    REPLACEMENT_ALLOW: { type: Boolean, default: false },
    REPLACEMENT_PERIOD: Number,
    EXPECTED_DELIVERY_IN_DAYS: Number,
    WARRANTY_CARD: String,
    RATING: Number,
    BASE_PRICE: String,
    DISCOUNTED_PERCENTAGE: String,
    WEIGHT: String,
    LENGTH: String,
    BREADTH: String,
    HEIGHT: String,
    EXPECTED_DELIVERY_CHARGES: String,
    IS_REFURBISHED: { type: Boolean, default: false }
}, { timestamps: true });

module.exports = mongoose.model('inventory_track', InventoryTrack);