const express = require('express');
const router = express.Router();
const mm = require('../utilities/globalModule')
var globalService = require('../services/global');

router

  .get('/inventoryRequest/processTokenRequest', require('../services/Inventory/inventoryRequest').processTokenRequest)
  .post('/inventoryRequest/updateRequestStatusEmail', require('../services/Inventory/inventoryRequest').updateRequestStatusEmail)
  .post('/inventoryRequest/updateRequestStatus', require('../services/Inventory/inventoryRequest').updateRequestStatus)

  // .post('/ImportFile', require('../services/importFile').bulkImport)
  


  .all('*', globalService.requireAuthentication)
   .post('/getPlaces', require('../services/global').getPlaces)
  .post('/getDirections', require('../services/global').getDirections)
  .post('/getPlaceDetails', require('../services/global').getPlaceDetails)
  //without token used methods
  .post('/user/login', require('../services/UserAccess/user').login)
  .post('/updateOrderDelivery', require('../services/ShipModule/shopOrder').updateOrderDelivery)
  .post('/app/login', require('../services/Masters/technician').login)
  .post('/app/global/search', require('../services/global').searchGlobally)
  .post('/serviceCategory/get', require('../services/Masters/category').get)
  .post('/serviceSubCategory/get', require('../services/Masters/subCategory').get)
  .get('/app/inventoryCategory', require('../services/Inventory/inventoryCategory').get)
  .get('/app/inventorySubCategory', require('../services/Inventory/inventorySubCategory').get)
  //newly added
  .post('/services/get', require('../services/Masters/service').get)
  .post('/app/getinventorySubCategory', require('../services/Inventory/inventorySubCategory').get)
  .post('/app/getinventoryCategory', require('../services/Inventory/inventoryCategory').get)
  //newly ended
  .post('/app/ServiceCategory', require('../services/Masters/category').getCategorys)
  .post('/app/global/webSearch', require('../services/global').globalDataForWeb)
  .post('/app/technician/sendOTP', require('../services/Masters/technician').sendOTP)
  .post('/app/technician/verifyOTP', require('../services/Masters/technician').verifyOTP)
  .post('/app/technician/sendOTPToConfirm', require('../services/Masters/technician').sendOTPtoConfirm)
  .post('/app/technician/verifyOTPToConfirm', require('../services/Masters/technician').verifyOTPToConfirm)
  .post('/app/technician/confirmByLink', require('../services/Masters/technician').confirmByLink)
  .use('/globalSetting', require('./globalSettings'))
  .post('/customer/sendOTP/', require('../services/Masters/customer').sendOTPToDevice)
  .post('/customer/verifyOTP/', require('../services/Masters/customer').verifyOTP)
  .post('/customer/customerlogin/', require('../services/Masters/customer').customerlogin)
  .post('/customer/changeCustomerPassword/', require('../services/Masters/customer').changeCustomerPassword)
  .post('/customer/sendotpforchangepassword/', require('../services/Masters/customer').sendotpforchangepassword)
  .post('/customer/verifyOTPpassword/', require('../services/Masters/customer').verifyOTPpassword)
  .post('/admin/sendOTP', require('../services/UserAccess/user').sendOTPToDevice)
  .post('/admin/verifyOTP', require('../services/UserAccess/user').verifyOTP)
  .post('/admin/changePassword', require('../services/UserAccess/user').changePassword)
  .post('/customer/registerOtp/', require('../services/Masters/customer').registerOtp)
  .post('/order/getServices/', require('../services/Order/order').getServices)
  .post('/order/getServicesForWeb/', require('../services/Order/order').getServicesForWeb)
  .post('/order/getCategories/', require('../services/Order/order').getCategoriesHierarchy)
  .post('/pincode/get', require('../services/Masters/pincode').get)
  .post('/state/get', require('../services/Masters/state').get)
  // .get('/app/getPoppulerServices/:TERRITORY_ID', require('../services/Masters/service').getPoppulerServices)
  .get('/app/getPoppulerServices/:CUSTOMER_TYPE/:TERRITORY_ID', require('../services/Masters/service').getPoppulerServices)
  .post('/app/getPoppulerServicesForWeb', require('../services/Masters/service').getPoppulerServicesForWeb)
  .post('/app/getPopularInvenotry', require('../services/Inventory/inventory').getPopularInvenotry)
  .post('/banner/get', require('../services/Masters/banner').get)
  .post('/brand/get', require('../services/Masters/brand').get)
  .post('/inventory/get', require('../services/Inventory/inventory').getForCart)
  .post('/inventory/getForCart', require('../services/Inventory/inventory').getForCart)
  .post('/territory/pincode/get', require('../services/Masters/territoryPincodeMapping').get)
  .post('/territory/pincode/get', require('../services/Masters/territoryPincodeMapping').get)
  .post('/customer/addCustomer', require('../services/Masters/customer').addCustomer)
  //.post('/shiprocketWebhook', require('../services/ShipModule/shopOrder').shiprocketWebhook)
  .post('/inventoryUnitMapping/get', require('../services/Inventory/inventoryUnitMapping').get)
  .post('/inventoryImageMapping/get', require('../services/Inventory/inventoryImageMapping').get)
  .post('/knowledgeBaseCategory/get', require('../services/Support/knowledgeBaseCategory').get)
  .post('/knowledgebaseSubCategory/get', require('../services/Support/knowledgebaseSubCategory').get)
  .post('/knowledgeBase/get', require('../services/Support/knowledgeBase').get)
  .post('/customerServiceFeedback/get', require('../services/Order/customerservicefeedback').get)
  .post('/customerServiceFeedback/getCustomerServiceFeedback', require('../services/Order/customerservicefeedback').getCustomerServiceFeedback)
  .post('/faq/get', require('../services/Support/faq').get)
  .post('/faqHead/get', require('../services/Support/faqHead').get)
  .all('*', globalService.requireAuthentication)
  .use('/api', globalService.checkToken)

  //user access
  .use('/api/form', require('./UserAccess/form'))
  .use('/api/role', require('./UserAccess/role'))
  .use('/api/roleDetails', require('./UserAccess/roleDetail'))
  .use('/api/user', require('./UserAccess/user'))

  //Masters
  .use('/api/organisation', require('./Masters/organisation'))
  .use('/api/branch', require('./Masters/branch'))
  .use('/api/country', require('./Masters/country'))
  .use('/api/state', require('./Masters/state'))
  .use('/api/city', require('./Masters/city'))
  .use('/api/pincode', require('./Masters/pincode'))
  .use('/api/skill', require('./Masters/skill'))
  .use('/api/orderStatus', require('./Masters/orderStatus'))
  .use('/api/jobCardStatus', require('./Masters/jobCardStatus'))
  .use('/api/technician', require('./Masters/technician'))
  .use('/api/vendor', require('./Masters/vendor'))
  .use('/api/customerCategory', require('./Masters/customerCategory'))
  .use('/api/customer', require('./Masters/customer'))
  .use('/api/customerEmailMaster', require('./Masters/customerEmailMaster'))
  .use('/api/customerAddress', require('./Masters/customerAddress'))
  .use('/api/emailTemplate', require('./Masters/emailTemplate'))
  .use('/api/smsTemplate', require('./Masters/smsTemplate'))
  .use('/api/whatsappTemplate', require('./Masters/whatsappTemplate'))
  .use('/api/appLanguage', require('./Masters/appLanguage'))
  .use('/api/language', require('./Masters/language'))
  .use('/api/unit', require('./Masters/unit'))
  .use('/api/backofficeTeam', require('./Masters/backofficeTeam'))
  .use('/api/category', require('./Masters/category'))
  .use('/api/subCategory', require('./Masters/subCategory'))
  .use('/api/service', require('./Masters/service'))
  .use('/api/territory', require('./Masters/territory'))
  .use('/api/territoryPincodeMapping', require('./Masters/territoryPincodeMapping'))
  .use('/api/territoryServicenOnAvailabilityMapping', require('./Masters/territoryServicenOnAvailabilityMapping'))
  .use('/api/currency', require('./Masters/currency'))
  .use('/api/countryCurrencyMapping', require('./Masters/countryCurrencyMapping'))
  .use('/api/tax', require('./Masters/tax')) // pending
  .use('/api/taxDetails', require('./Masters/taxDetails'))//pending
  .use('/api/taxStateMapping', require('./Masters/taxStateMapping'))
  .use('/api/backofficeTerritoryMapping', require('./Masters/backofficeTerritoryMapping'))
  .use('/api/serviceSkillMapping', require('./Masters/serviceSkillMapping'))
  .use('/api/customerTechnicianMapping', require('./Masters/customerTechnicianMapping'))
  .use('/api/technicianPincodeMapping', require('./Masters/technicianPincodeMapping'))
  .use('/api/technicianSkillMapping', require('./Masters/technicianSkillMapping'))
  .use('/api/technicianServiceCostMapping', require('./Masters/technicianServiceCostMapping'))
  .use('/api/technicianLanguageMapping', require('./Masters/technicianLanguageMapping'))
  .use('/api/technicianAvailabilityCalendar', require('./Masters/technicianAvailabilityCalendar'))
  .use('/api/technicianConfigurations', require('./Masters/technicianConfigurations'))
  .use('/api/vendorServiceCostMapping', require('./Masters/vendorServiceCostMapping'))
  .use('/api/coupon', require('./Masters/coupon'))
  .use('/api/couponCodeCountryMapping', require('./Masters/couponCodeCountryMapping'))
  .use('/api/couponUsage', require('./Masters/couponUsage'))
  .use('/api/notification', require('./Masters/notification'))
  .use('/api/district', require('./Masters/district'))
  .use('/api/serviceDocument', require('./Masters/serviceDocument'))
  .use('/api/serviceDocumemtMapping', require('./Masters/serviceDocumemtMapping'))
  .use('/api/b2bAvailabilityMapping', require('./Masters/b2bAvailabilityMapping'))
  .use('/api/serviceLogs', require('./Masters/service'))
  .use('/api/vendorTerritoryMapping', require('./Masters/vendorTerritoryMapping'))
  .use('/api/hsn', require('./Masters/hsn'))
  .use('/api/banner', require('./Masters/banner'))
  .use('/api/technicianSkillRequest', require('./Masters/technicianSkillRequest'))
  .use('/api/warehouseTerritoryMapping', require('./Masters/warehouseTerritoryMapping'))
  .use('/api/techniciancertificaterequest', require('./Masters/techniciancertificaterequest'))
  .use('/api/backofficeDepartmentMapping', require('./Masters/backofficeDepartmentMapping'))
  .use('/api/helpDocumentCategory', require('./Masters/helpDocumentCategory'))
  .use('/api/helpDocumentSubCategory', require('./Masters/helpDocumentSubCategory'))
  .use('/api/jobTraining', require('./Masters/jobTraining'))
  .use('/api/technicianProfileUpdateRequest', require('./Masters/technicianProfileupdaterequest'))
  .use('/api/brand', require('./Masters/brand'))
  .use('/api/dashboard', require('./Masters/dashboard'))
  .use('/api/customerEmailMapping', require('./Masters/customerEmailMapping'))
  .use('/api/iana', require('./Masters/iana'))




  //UPLODS 
  .post('/api/upload/:folderName', globalService.uploadFiles)

  //dowload
  .get('/api/getFile/:folderName/:filename', globalService.downloadFiles)
  .post('/api/getFileLink', globalService.getDownloadLink)

  // order 
  .use('/api/cart', require('./Order/cart'))
  .use('/api/cartItemDetails', require('./Order/cartItemDetails'))
  .use('/api/cartSummaryDetails', require('./Order/cartSummaryDetails'))
  .use('/api/order', require('./Order/order'))
  .use('/api/orderMasterAddressMap', require('./Order/orderMasterAddressMap'))
  .use('/api/orderSummeryDetails', require('./Order/orderSummeryDetails'))
  .use('/api/orderDetails', require('./Order/orderDetails'))
  // .use('/api/orderChat', require('./Order/orderChat'))
  // .use('/api/orderChatDetails', require('./Order/orderChatDetails'))
  .use('/api/orderPaymentDetails', require('./Order/orderPaymentDetails'))
  .use('/api/orderPaymentDetails', require('./Order/orderPaymentDetails'))
  .use('/api/orderStatusLog', require('./Order/orderStatusLog'))
  .use('/api/jobCard', require('./Order/jobCard'))
  .use('/api/jobCardTechnicianMapping', require('./Order/jobCardTechnicianMapping'))
  .use('/api/jobCardSchedulingDetails', require('./Order/jobCardSchedulingDetails'))
  .use('/api/jobCardStatusLog', require('./Order/jobCardStatusLog'))
  .use('/api/jobCardInventoryMapping', require('./Order/jobCardInventoryMapping'))
  .use('/api/invoice', require('./Order/invoice'))
  .use('/api/invoiceItemDetails', require('./Order/invoiceItemDetails'))
  .use('/api/orderTechnicianLocationTrack', require('./Order/orderTechnicianLocationTrack'))
  .use('/api/technicianTimeTrack', require('./Order/technicianTimeTrack'))
  .use('/api/technicianActionLogs', require('./Order/technicianActionLogs'))
  // .use('/api/coupontransactions', require('./Order/coupontransactions'))
  .use('/api/orderrefundtransactions', require('./Order/orderrefundtransactions'))
  .use('/api/ordercancellationtransactions', require('./Order/ordercancellationtransactions'))
  .use('/api/jobcardchatdetails', require('./Order/jobcardchatdetails'))
  .use('/api/jobcardchat', require('./Order/jobcardchat'))
  .use('/api/techniciancustomerfeedback', require('./Order/techniciancustomerfeedback'))
  .use('/api/customertechnicianfeedback', require('./Order/customertechnicianfeedback'))
  .use('/api/customerServiceFeedback', require('./Order/customerservicefeedback'))
  .use('/api/invoicepaymentdetails', require('./Order/invoicepaymentdetails'))
  .use('/api/orderInvoiceMapping', require('./Order/orderinvoicemapping'))
  .use('/api/technicianJobSchedule', require('./Order/technicianJobSchedule'))
  .use('/api/jobPhotosDetails', require('./Order/jobPhotosDetails'))
  .use('/api/cancleOrderReason', require('./Order/cancleOrderReason'))
  .use('/api/jobRescheduleTransactions', require('./Order/jobRescheduleTransactions'))

  // Inventory
  .use('/api/warehouse', require('./Inventory/warehouse'))
  .use('/api/inventoryCategory', require('./Inventory/inventoryCategory'))
  .use('/api/inventorySubCategory', require('./Inventory/inventorySubCategory'))
  .use('/api/inventory', require('./Inventory/inventory'))
  .use('/api/warehouseLocations', require('./Inventory/warehouseLocations'))
  .use('/api/inventoryTransactions', require('./Inventory/inventoryTransactions'))
  .use('/api/inventoryWarehouseStockManagement', require('./Inventory/inventoryWarehouseStockManagement'))
  .use('/api/inventoryMovement', require('./Inventory/inventoryMovement'))
  .use('/api/inventoryMovementDetails', require('./Inventory/inventoryMovementDetails'))
  .use('/api/inventoryPurchase', require('./Inventory/inventoryPurchase'))
  .use('/api/inventoryPurchaseDetails', require('./Inventory/inventoryPurchaseDetails'))
  .use('/api/inventoryUnitMapping', require('./Inventory/inventoryUnitMapping'))
  .use('/api/inventoryAdjustment', require('./Inventory/inventoryAdjustment'))
  .use('/api/inventoryItemSerialDetails', require('./Inventory/inventoryItemSerialDetails'))
  .use('/api/inventoryRequest', require('./Inventory/inventoryRequest'))
  .use('/api/inventoryRequestDetails', require('./Inventory/inventoryRequestDetails'))
  .use('/api/varient', require('./Inventory/varient'))
  .use('/api/inventoryImageMapping', require('./Inventory/inventoryImageMapping'))
  .use('/api/inventoryInward', require('./Inventory/inventoryInward'))
  .use('/api/inventoryInwardDetails', require('./Inventory/inventoryInwardDetails'))
  .use('/api/inventoryTransactions', require('./Inventory/inventoryTransactions'))
  .use('/api/inventoryAccountTransaction', require('./Inventory/inventoryAccountTransaction'))
  .use('/api/technicianMovement', require('./Inventory/inventoryTechnicianMovement'))
  .use('/api/technicianMovementDetails', require('./Inventory/inventoryTechnicianMovementDetails'))
  .use('/api/customerMovement', require('./Inventory/inventoryCustomerMovement'))
  .use('/api/customerMovementDetails', require('./Inventory/inventoryCustomerMovementDetails'))



  // Support
  .use('/api/knowledgeBaseCategory', require('./Support/knowledgeBaseCategory'))
  .use('/api/knowledgebaseSubCategory', require('./Support/knowledgebaseSubCategory'))
  .use('/api/knowledgeBase', require('./Support/knowledgeBase'))
  .use('/api/knowledgeBaseFeedbackTransactions', require('./Support/knowledgeBaseFeedbackTransactions'))
  .use('/api/supportCategory', require('./Support/supportCategory'))
  .use('/api/supportSubCategory', require('./Support/supportSubCategory'))
  .use('/api/ticket', require('./Support/ticket'))
  .use('/api/ticketDetails', require('./Support/ticketDetails'))
  .use('/api/faqHead', require('./Support/faqHead'))
  .use('/api/faq', require('./Support/faq'))
  .use('/api/faqResponses', require('./Support/faqResponse'))
  .use('/api/ticketLogDetails', require('./Support/ticketLogDetails'))
  .use('/api/ticketGroup', require('./Support/ticketGroup'))
  .use('/api/ticketFaqMapping', require('./Support/ticketFaqMapping'))
  .use('/api/tickdeskDepartmentAdminMapping', require('./Support/tickdeskDepartmentAdminMapping'))
  .use('/api/tickdeskSupportUserMapping', require('./Support/tickdeskSupportUserMapping'))
  .use('/api/department', require('./Support/department'))


  //config
  .use('/api/emailServiceConfig', require('./Config/emailServiceConfig'))
  .use('/api/smsServiceConfig', require('./Config/smsServiceConfig'))
  .use('/api/whatsappserviceconfig', require('./Config/whatsappserviceconfig'))
  .use('/api/customerConfigurations', require('./Config/customerConfigurations'))
  .use('/api/paymentGateway', require('./Config/paymentGateway'))
  .use('/api/paymentGatewayConfigurations', require('./Config/paymentGatewayConfigurations'))
  .use('/api/orgnizationServiceCalender', require('./Config/orgnizationServiceCalender'))
  .use('/api/searchData', require('./Config/search'))
  .use('/api/saveFilter', require('./Config/saveFilter'))
  .use('/api/global/search', require('../services/global').searchGlobally)
  .use('/api/globalTimeSlotConfig', require('./Config/globalTimeSlotConfig'))
  .use('/api/globalTimeSlotMapping', require('./Config/globalTimeSlotMapping'))
  .use('/api/tempaltecategory', require('./Config/tempaltecategory'))
  .use('/api/placeholder', require('./Config/placeholder'))
  .use('/api/paymentGatewayTransactions', require('./Config/paymentGatewayTransactions'))


  //reports
  .use('/api/reports', require('./Reports/reports'))
  .use('/api/inventoryReports', require('./Reports/inventoryReports'))
  .use('/api/ticketGroupwiseSummaryReport', require('./Reports/ticketGroupwiseSummaryReport'))
  .use('/api/ticketGroupwiseDetailedReport', require('./Reports/ticketGroupwiseDetailedReport'))
  .use('/api/ticketTransferReport', require('./Reports/ticketTransferReport'))
  .use('/api/ticketResolutionTimeGroupwise', require('./Reports/ticketResolutionTimeGroupwise'))
  .use('/api/ticketSupportAgentwiseDetailedReport', require('./Reports/ticketSupportAgentwiseDetailedReport'))
  .use('/api/reports/coupon', require('./Reports/coupon'))


  //Mongo API methods
  .use('/api/technicianLocationTrack', require('../mongoRoutes/technicianLocationTrack'))
  .use('/api/technicianActivityCalender', require('../mongoRoutes/technicianActivityCalender'))
  .use('/api/technicainDayLog', require('../mongoRoutes/technicainDayLog'))
  .use('/api/jobchat', require('../mongoRoutes/jobCardChat'))
  .use('/api/orderChat', require('../mongoRoutes/orderChat'))
  .use('/api/inventoryActivityLogs', require('../mongoRoutes/inventoryActivityLogs'))
  .use('/api/InventoryTrack', require('../mongoRoutes/InventoryTrack'))
  .use('/api/shopOrderActionLog', require('../mongoRoutes/shopOrderActionLog'))
  .use('/api/channel', require('../mongoRoutes/channel'))
  .use('/api/channelSubscribedUsers', require('../mongoRoutes/channelSubscribedUsers'))


  //Coupon Module
  .use('/api/couponType', require('./Masters/couponType'))
  .use('/api/coupon', require('./Masters/coupon'))
  .use('/api/couponCodeInventoryMapping', require('./Masters/couponCodeInventoryMapping'))
  .use('/api/couponCodeServiceMapping', require('./Masters/couponCodeServiceMapping'))
  .use('/api/couponTransaction', require('./Masters/couponTransaction'))

  //shop module
  .use('/api/shopOrder', require('./ShipModule/shopOrder'))
  .use('/api/shopOrderAddressMap', require('./ShipModule/shopOrderAddressmap'))
  .use('/api/shopOrderSummaryDetails', require('./ShipModule/shopOrderSummaryDetails'))
  .use('/api/shopOrderDetails', require('./ShipModule/shopOrderdetails'))
  .use('/api/shipRocketOrderDetails', require('./ShipModule/shipRocketOrderDetails'))
  .use('/api/shiprocketWebhookLogs', require('./ShipModule/shiprocketWebhookLogs'))
  .use('/api/productReturns', require('./ShipModule/productReturns'))
  .use('/api/shopOrderActionLog', require('../mongoRoutes/shopOrderActionLog'))
  .use('/api/customerProductFeedback', require('./ShipModule/customerProductFeedback'))
  .use('/api/shopOrdercancellationtransactions', require('./ShipModule/shopOrdercancellationtransactions'))
  .use('/api/shiprocket', require('./ShipModule/shiprocket'))
  .use('/api/pickupLocation', require('./ShipModule/pickupLocation'))
  .use('/api/shiprocketLoginInfo', require('./ShipModule/shiprocketLoginInfo'))




module.exports = router;
